baseURL: https://chatgptwith.me
languageCode: en-us
title: ChatGPT with Me
theme: hugo-theme-mini

defaultContentLanguage: en

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

paginate: 10

markup:
  highlight:
    guessSyntax: true
    style: emacs
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  goldmark:
    renderer:
      unsafe: true

social:
  github: https://github.com/AnimMouse/ChatGPT-with-Me-Website

params:
  author: Anim Mouse and ChatGPT
  bio: Let's chat with ChatGPT
  description: A website that publishes conversations with ChatGPT
  enableRSS: true
  enableComments: false
  enableGoogleAnalytics: false
  showToc: true
  showPowerBy: true
  math: false
  hiddenPostSummaryInHomePage: false
  copyright: ''

#  links:
#    - name: 
#      path: 