name: Update Hugo
on:
  schedule:
    - cron: '7 11 * * 0'
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}
  
jobs:
  update:
    uses: AnimMouse/Cloudflare-Pages-Variable-Action/.github/workflows/update-hugo.yaml@v1
    with:
      project_name: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
      account_id: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
    secrets:
      api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}