name: Update Hugo
on:
  schedule:
    - cron: '7 11 * * 0'
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}
  
jobs:
  update:
    uses: AnimMouse/animmouse-website/.github/workflows/update-hugo-cloudflare-pages.yaml@main
    with:
      project_name: ${{ vars.CF_PROJECT_NAME }}
      account_id: ${{ vars.CF_ACCOUNT_ID }}
    secrets:
      api_token: ${{ secrets.CF_API_TOKEN }}